str1 = "abcdefghijklmnopqrstuvwxyz"
print(str1.upper())
print(str1.lower())
print(str1.strip(' '))
print(str1.title())
print(str1[6:11])
print(str1.capitalize())
print(str1.swapcase())
print(str1.center(20, "*"))
print(str1.count("l"))
print(str1.find("l"))
print(str1.replace("l", "a"))
print(str1.split(" "))
print(str1.splitlines())
print(str1.startswith("H"))
print(str1.endswith("d"))
print(str1.index("o"))
print(str1.rfind("o"))
print(str1.isalnum())
print(str1.isalpha())
print(str1[14:5:-1])