# a =list(map(eval,input("enter the values separate with (\",\") symbol:").split(",")))
a =['a','b','c','d']
print(*a)
a.append("e")
print(a)
a.extend('f')
print(a)
a.insert(3,'g')
print(a)
print(a.index('e'))
a.pop()
print(a)
a.sort()
print(a)
a.reverse()
print(a)
print(len(a))
print(a[1:4])
p = 'a' in a
print(p)
a.clear()
print(a)
