a=4
b=2
print("Arithmetic Operation")
print("add",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)
print("mod",a%b)
print("pow",a**b)
print("floordiv",a//b)
print("bitwise operation")
print("bitwise and",a&b)
print("bitwise or",a|b)
print("bitwise xor",a^b)
print("bitwise not",~a)
print("right shift",a>>b)
print("left shift",a<<b)
print("absolute value",abs(a))
print("round off",round(a))