a=eval(input("Enter any value:"))
print(type(a))
a=int(input("Enter any int value:"))
print(a)
a=float(input("Enter any float value:"))
print(a)
a=complex(input("Enter any complex value:"))
print(a)
a=str(input("Enter any string value:"))
print(a)
