# tup =tuple(map(eval,input().split(',')))
tup =(1,2,5,3,4)
print(*tup)
print(tup.count(2))
print(tup.index(3))
print(tup.index(3,1))
print(tup.index(3,1,4))
print(max(tup))
print(min(tup))
print(tup[2])
tup2 =(4,5,6)
tup =tup+tup2
print(tup)
print(tup2*2)